spring:
  datasource:
    url: jdbc:mysql://localhost:3306
    username: developer
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 5000
  servlet:
    context-path: /
